/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as MalwareDetectionRouteImport } from './routes/malware-detection'
import { Route as NetworkDetectionRouteImport } from './routes/network-detection'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const MalwareDetectionRoute = MalwareDetectionRouteImport.update({
  id: '/malware-detection',
  path: '/malware-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkDetectionRoute = NetworkDetectionRouteImport.update({
  id: '/network-detection',
  path: '/network-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/documentation': typeof DocumentationRoute
  '/malware-detection': typeof MalwareDetectionRoute
  '/network-detection': typeof NetworkDetectionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/documentation': typeof DocumentationRoute
  '/malware-detection': typeof MalwareDetectionRoute
  '/network-detection': typeof NetworkDetectionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/documentation': typeof DocumentationRoute
  '/malware-detection': typeof MalwareDetectionRoute
  '/network-detection': typeof NetworkDetectionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/documentation'
    | '/malware-detection'
    | '/network-detection'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/documentation'
    | '/malware-detection'
    | '/network-detection'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/documentation'
    | '/malware-detection'
    | '/network-detection'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DocumentationRoute: typeof DocumentationRoute
  MalwareDetectionRoute: typeof MalwareDetectionRoute
  NetworkDetectionRoute: typeof NetworkDetectionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malware-detection': {
      id: '/malware-detection'
      path: '/malware-detection'
      fullPath: '/malware-detection'
      preLoaderRoute: typeof MalwareDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-detection': {
      id: '/network-detection'
      path: '/network-detection'
      fullPath: '/network-detection'
      preLoaderRoute: typeof NetworkDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocumentationRoute: DocumentationRoute,
  MalwareDetectionRoute: MalwareDetectionRoute,
  NetworkDetectionRoute: NetworkDetectionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
